### ISSUE TITLE
Parse error: syntax error, unexpected '[' in instagram_post.php on line 51

### ISSUE THREAD

**Issue by blackthornecl** [aran112000/Instagram-Image-Upload-API#1]
`Parse error: syntax error, unexpected '[' in instagram_post.php on line 51
`
what i did wrong?

regards!

**Comment by aran112000** [comment]
It would appear you're using an old, non supported version of PHP (< 5.4) where sort array syntax was introduced. 

This can be solved simply though, simply replace instances of the short array declarations from their current `[]` structure to use `array()` instead. 

Hope this helps.

**Comment by blackthornecl** [comment]
Mmmm im using php 5.3 its too old?

now i get this:

`Parse error: syntax error, unexpected T_DOUBLE_ARROW in instagram_post.php on line 107`
